// Generated by cpp11: do not edit by hand
// clang-format off

#include "lignum_types.hpp"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// r_wrapper.cpp
model_ptr_t load_model_cpp(std::string filepath, std::string format);
extern "C" SEXP _lignum_load_model_cpp(SEXP filepath, SEXP format) {
  BEGIN_CPP11
    return cpp11::as_sexp(load_model_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(filepath), cpp11::as_cpp<cpp11::decay_t<std::string>>(format)));
  END_CPP11
}
// r_wrapper.cpp
void save_model_cpp(model_ptr_t model, std::string filepath);
extern "C" SEXP _lignum_save_model_cpp(SEXP model, SEXP filepath) {
  BEGIN_CPP11
    save_model_cpp(cpp11::as_cpp<cpp11::decay_t<model_ptr_t>>(model), cpp11::as_cpp<cpp11::decay_t<std::string>>(filepath));
    return R_NilValue;
  END_CPP11
}
// r_wrapper.cpp
doubles predict_cpp(model_ptr_t model, doubles X_flat, int n_samples, int n_features, bool raw_score, int n_jobs);
extern "C" SEXP _lignum_predict_cpp(SEXP model, SEXP X_flat, SEXP n_samples, SEXP n_features, SEXP raw_score, SEXP n_jobs) {
  BEGIN_CPP11
    return cpp11::as_sexp(predict_cpp(cpp11::as_cpp<cpp11::decay_t<model_ptr_t>>(model), cpp11::as_cpp<cpp11::decay_t<doubles>>(X_flat), cpp11::as_cpp<cpp11::decay_t<int>>(n_samples), cpp11::as_cpp<cpp11::decay_t<int>>(n_features), cpp11::as_cpp<cpp11::decay_t<bool>>(raw_score), cpp11::as_cpp<cpp11::decay_t<int>>(n_jobs)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_lignum_load_model_cpp", (DL_FUNC) &_lignum_load_model_cpp, 2},
    {"_lignum_predict_cpp",    (DL_FUNC) &_lignum_predict_cpp,    6},
    {"_lignum_save_model_cpp", (DL_FUNC) &_lignum_save_model_cpp, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_lignum(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
