# Generated by cpp11: do not edit by hand

load_model_cpp <- function(filepath, format) {
  .Call(`_lignum_load_model_cpp`, filepath, format)
}

save_model_cpp <- function(model, filepath) {
  invisible(.Call(`_lignum_save_model_cpp`, model, filepath))
}

predict_cpp <- function(model, X_flat, n_samples, n_features, raw_score, n_jobs) {
  .Call(`_lignum_predict_cpp`, model, X_flat, n_samples, n_features, raw_score, n_jobs)
}
